import { forwardRef } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { FiPhone, FiHash, FiHeart } from 'react-icons/fi';
import { getTemplateById } from '../../utils/cardTemplates';
import { formatCurrency, formatDate } from '../../utils/formatters';
import { getOptimizedUrl } from '../../services/cloudinaryService';
import { useImageStatus } from '../../hooks/useImageStatus';
import { buildCardUrl } from '../../utils/share';
import './ContributionCard.css';

/**
 * The personalized contribution card. Forward-ref so it can be captured by
 * html-to-image / jsPDF for downloads.
 */
const ContributionCard = forwardRef(function ContributionCard({ event, card }, ref) {
  const template = getTemplateById(card?.templateId || event?.templateId);
  const banner = event?.bannerUrl ? getOptimizedUrl(event.bannerUrl, { width: 720, height: 360 }) : '';
  const bannerStatus = useImageStatus(banner);
  const showBanner = bannerStatus === 'loaded';
  const cardUrl = card?.id ? buildCardUrl(card.id) : '';

  return (
    <div
      ref={ref}
      className="contribution-card"
      style={{
        background: template.preview,
        color: template.textColor,
        fontFamily: template.fontFamily,
        '--card-accent': template.accent,
      }}
    >
      <div className="contribution-card-banner" style={showBanner ? { backgroundImage: `url(${banner})` } : undefined}>
        {!showBanner && <FiHeart className="contribution-card-banner-fallback" />}
        <div className="contribution-card-banner-overlay" />
        <div className="contribution-card-banner-text">
          <span className="contribution-card-eyebrow">You&apos;re invited to celebrate</span>
          <h2>{event?.eventName}</h2>
          <p>
            {event?.brideName} &amp; {event?.groomName} · {formatDate(event?.eventDate)}
          </p>
        </div>
      </div>

      <div className="contribution-card-body">
        <div className="contribution-card-main">
          <p className="contribution-card-label">Contribution card for</p>
          <h3 className="contribution-card-name">{card?.contributorName}</h3>

          <dl className="contribution-card-details">
            <div>
              <dt>
                <FiPhone /> Phone number
              </dt>
              <dd>{card?.contributorPhone}</dd>
            </div>
            <div>
              <dt>Contribution amount</dt>
              <dd className="contribution-card-amount">{formatCurrency(card?.amount)}</dd>
            </div>
            <div>
              <dt>
                <FiHash /> Invitation code
              </dt>
              <dd className="contribution-card-code">{card?.invitationCode}</dd>
            </div>
          </dl>
        </div>

        <div className="contribution-card-qr">
          {cardUrl && <QRCodeSVG value={cardUrl} size={108} bgColor="transparent" fgColor={template.textColor} level="M" />}
          <span>Scan to verify</span>
        </div>
      </div>

      <footer className="contribution-card-footer">
        <span>Generated by Michango</span>
        <span>{event?.location}</span>
      </footer>
    </div>
  );
});

export default ContributionCard;
